//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning_Cloud_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressManager
    {
        public int AMID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AMUser { get; set; }
        public string AMTel { get; set; }
        public string AMAddress { get; set; }
        public Nullable<bool> AMMark { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
