//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning_Cloud_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int BookID { get; set; }
        public Nullable<int> BSID { get; set; }
        public string BookTitle { get; set; }
        public string BookAuthor { get; set; }
        public string BookPublish { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> BookCount { get; set; }
        public Nullable<decimal> BookMoney { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public string BookDesc { get; set; }
        public string BookAuthorDesc { get; set; }
        public string BookComm { get; set; }
        public string BookContent { get; set; }
        public Nullable<int> BookSale { get; set; }
        public Nullable<int> BookDeport { get; set; }
        public Nullable<bool> BookIsBuy { get; set; }
        public Nullable<bool> BookIsHot { get; set; }
        public Nullable<bool> BookIsDelete { get; set; }
        public Nullable<System.DateTime> BookBuyDate { get; set; }
        public Nullable<System.DateTime> BookHotDate { get; set; }
    
        public virtual BSCategory BSCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
