//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning_Cloud_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAppraise
    {
        public int BAID { get; set; }
        public Nullable<int> ODID { get; set; }
        public string BADesc { get; set; }
        public Nullable<int> BAPoint { get; set; }
        public Nullable<System.DateTime> BADate { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
