//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning_Cloud_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.BookAppraise = new HashSet<BookAppraise>();
        }
    
        public int ODID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<decimal> ODPrice { get; set; }
        public Nullable<int> ODCount { get; set; }
        public Nullable<decimal> ODMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAppraise> BookAppraise { get; set; }
        public virtual Books Books { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
